// Generated by CoffeeScript 1.7.1
(function() {
  var Backbone, ClientList, ProjectList, SettingsList, requirejs, _ref;

  requirejs = require("requirejs");

  Backbone = require('./backbone-socketio-backend');

  _ref = requirejs("./../public/lib/models"), ProjectList = _ref.ProjectList, ClientList = _ref.ClientList, SettingsList = _ref.SettingsList;

  exports.Clients = new ClientList(null, {
    backend: "clients"
  });

  exports.Projects = new ProjectList(null, {
    backend: "projects",
    clients: exports.Clients
  });

  exports.Settings = new SettingsList(null, {
    backend: "settings"
  });

  Backbone.connector.connect(exports.Projects, true);

  Backbone.connector.connect(exports.Clients);

  Backbone.connector.connect(exports.Settings, true);

  exports.Projects.fetch();

  exports.Settings.fetch({
    success: function() {
      if (exports.Settings.size() === 0) {
        return exports.Settings.create({}, {
          wait: true
        });
      }
    }
  });

}).call(this);
