// Generated by CoffeeScript 1.7.1
(function() {
  var FileWatcher, fs, _;

  fs = require("fs");

  _ = require("underscore")._;

  FileWatcher = (function() {
    function FileWatcher() {
      this.watchers = {};
      this.modifiedTimes = {};
      this.isWindows = !!process.platform.match(/^win/i);
    }

    FileWatcher.prototype.watch = function(path, callback) {
      if (this.watchers[path]) {
        return;
      }
      if (this.isWindows) {
        this.modifiedTimes[path] = (fs.statSync(path)).mtime.getTime();
        return this.watchers[path] = fs.watch(path, (function(_this) {
          return function(event) {
            var modifiedTimes;
            modifiedTimes = (fs.statSync(path)).mtime.getTime();
            if (event === "change" && modifiedTimes !== _this.modifiedTimes[path]) {
              _this.modifiedTimes[path] = modifiedTimes;
              return callback();
            }
          };
        })(this));
      } else {
        fs.watchFile(path, {
          interval: 100
        }, function(curr, prev) {
          if (curr.mtime.getTime() !== prev.mtime.getTime()) {
            return callback();
          }
        });
        return this.watchers[path] = 1;
      }
    };

    FileWatcher.prototype.unwatch = function(path) {
      if (!this.watchers[path]) {
        return;
      }
      if (this.isWindows) {
        this.watchers[path].close();
      } else {
        fs.unwatchFile(path);
      }
      return delete this.watchers[path];
    };

    return FileWatcher;

  })();

  exports.FileWatcher = FileWatcher;

  exports.watcher = new FileWatcher;

}).call(this);
